version: '3.8'
services:
  lanchonete-postgresql:
    extends:
      file: postgresql.yml
      service: lanchonete-postgresql
    container_name: lanchonete-postgresql

networks:
  default:
    external:
      name: docker_default